version: 2.1
orbs:
  snyk: snyk/snyk@2.1.0
jobs:
  test-and-snyk:
    machine:
      image: default
    steps:
      - run: docker pull golang:1.22
      - checkout
      - run: "docker run --privileged=true
            -v /home/circleci/project/:/go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            -w /go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            golang:1.22 sh -c 'git config --global url.\"https://'$GITHUB_USERNAME':'$GITHUB_PASSWORD'@github.com\".insteadOf \"https://github.com\" && go env -w GOPRIVATE=github.com/goalbook && go mod download && go test -v -p 1 ./...'"
      - snyk/scan:
          fail-on-issues: false
          organization: goalbook
workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - test-and-snyk:
          context:
            - snyk